# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0719dfdce63c22f06fb6bdf3cc13afde74509b7a2181ba71cb27d1b6f7aeacdde4961e59e732c3e2f37028a3ad2cfb8011b1c24f82d4e57b654a66600269e4

test:
  secret_key_base: e0a25b31630f54a9699b67098b72176db5c076e73546dbaed9f4a610262f404f8bb4a4cb20765e82b138f14b01cab2257d2b05be65fd6b107498154ee28011a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
